version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lms-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_lms:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_lms: